using System;
#nullable enable

namespace CDMApi.Features.Systemusers
{
    public class SystemuserModel
    {
        public Guid Id { get; set; }
        public DateTime? SinkCreatedOn { get; set; }
        public DateTime? SinkModifiedOn { get; set; }
        public Int32? address2_shippingmethodcode { get; set; }
        public Int32? accessmode { get; set; }
        public Int32? address1_shippingmethodcode { get; set; }
        public Int32? preferredaddresscode { get; set; }
        public Int32? preferredemailcode { get; set; }
        public Int32? caltype { get; set; }
        public Int32? address1_addresstypecode { get; set; }
        public Int32? incomingemaildeliverymethod { get; set; }
        public Int32? preferredphonecode { get; set; }
        public Int32? outgoingemaildeliverymethod { get; set; }
        public Int32? invitestatuscode { get; set; }
        public Int32? emailrouteraccessapproval { get; set; }
        public Int32? address2_addresstypecode { get; set; }
        public Boolean? setupuser { get; set; }
        public Boolean? defaultfilterspopulated { get; set; }
        public Boolean? isintegrationuser { get; set; }
        public Boolean? issyncwithdirectory { get; set; }
        public Boolean? isactivedirectoryuser { get; set; }
        public Boolean? islicensed { get; set; }
        public Boolean? displayinserviceviews { get; set; }
        public Boolean? isemailaddressapprovedbyo365admin { get; set; }
        public Boolean? isdisabled { get; set; }
        public Guid? queueid { get; set; }
        public String? queueid_entitytype { get; set; }
        public Guid? calendarid { get; set; }
        public String? calendarid_entitytype { get; set; }
        public Guid? modifiedonbehalfby { get; set; }
        public String? modifiedonbehalfby_entitytype { get; set; }
        public Guid? defaultmailbox { get; set; }
        public String? defaultmailbox_entitytype { get; set; }
        public Guid? createdonbehalfby { get; set; }
        public String? createdonbehalfby_entitytype { get; set; }
        public Guid? businessunitid { get; set; }
        public String? businessunitid_entitytype { get; set; }
        public Guid? positionid { get; set; }
        public String? positionid_entitytype { get; set; }
        public Guid? transactioncurrencyid { get; set; }
        public String? transactioncurrencyid_entitytype { get; set; }
        public Guid? parentsystemuserid { get; set; }
        public String? parentsystemuserid_entitytype { get; set; }
        public Guid? mobileofflineprofileid { get; set; }
        public String? mobileofflineprofileid_entitytype { get; set; }
        public Guid? modifiedby { get; set; }
        public String? modifiedby_entitytype { get; set; }
        public Guid? territoryid { get; set; }
        public String? territoryid_entitytype { get; set; }
        public Guid? createdby { get; set; }
        public String? createdby_entitytype { get; set; }
        public String? fullname { get; set; }
        public String? address1_postofficebox { get; set; }
        public Int32? identityid { get; set; }
        public Int32? versionnumber { get; set; }
        public String? address1_line1 { get; set; }
        public String? address2_stateorprovince { get; set; }
        public String? yomifullname { get; set; }
        public String? address1_line3 { get; set; }
        public String? salutation { get; set; }
        public String? address2_telephone3 { get; set; }
        public Guid? organizationid { get; set; }
        public String? address2_county { get; set; }
        public String? entityimage_url { get; set; }
        public String? sharepointemailaddress { get; set; }
        public String? address1_postalcode { get; set; }
        public Int32? utcconversiontimezonecode { get; set; }
        public String? address2_fax { get; set; }
        public String? organizationidname { get; set; }
        public String? address2_postofficebox { get; set; }
        public Int32? address1_utcoffset { get; set; }
        public String? address2_postalcode { get; set; }
        public String? yomifirstname { get; set; }
        public String? positionidname { get; set; }
        public String? address2_line1 { get; set; }
        public Int32? passporthi { get; set; }
        public String? modifiedbyyominame { get; set; }
        public String? createdonbehalfbyname { get; set; }
        public String? address2_upszone { get; set; }
        public String? employeeid { get; set; }
        public Int32? userlicensetype { get; set; }
        public Int32? passportlo { get; set; }
        public String? windowsliveid { get; set; }
        public String? queueidname { get; set; }
        public String? governmentid { get; set; }
        public String? address2_telephone1 { get; set; }
        public String? mobilephone { get; set; }
        public String? address1_telephone2 { get; set; }
        public String? address1_telephone3 { get; set; }
        public String? modifiedonbehalfbyyominame { get; set; }
        public Int32? address2_utcoffset { get; set; }
        public String? personalemailaddress { get; set; }
        public String? address1_county { get; set; }
        public String? address2_composite { get; set; }
        public Guid? stageid { get; set; }
        public DateTime? modifiedon { get; set; }
        public String? homephone { get; set; }
        public String? createdbyname { get; set; }
        public Decimal? address2_longitude { get; set; }
        public String? jobtitle { get; set; }
        public String? address1_telephone1 { get; set; }
        public DateTime? createdon { get; set; }
        public String? mobileofflineprofileidname { get; set; }
        public Int32? entityimage_timestamp { get; set; }
        public DateTime? overriddencreatedon { get; set; }
        public Decimal? address1_latitude { get; set; }
        public String? domainname { get; set; }
        public String? createdbyyominame { get; set; }
        public Guid? applicationid { get; set; }
        public String? modifiedonbehalfbyname { get; set; }
        public String? address1_upszone { get; set; }
        public String? address2_line2 { get; set; }
        public String? yomilastname { get; set; }
        public String? firstname { get; set; }
        public String? parentsystemuseridyominame { get; set; }
        public String? photourl { get; set; }
        public String? createdonbehalfbyyominame { get; set; }
        public String? yammeruserid { get; set; }
        public String? userpuid { get; set; }
        public String? address2_telephone2 { get; set; }
        public String? modifiedbyname { get; set; }
        public String? address2_name { get; set; }
        public String? transactioncurrencyidname { get; set; }
        public Decimal? exchangerate { get; set; }
        public Guid? processid { get; set; }
        public String? title { get; set; }
        public String? yammeremailaddress { get; set; }
        public String? address1_composite { get; set; }
        public String? mobilealertemail { get; set; }
        public String? address1_line2 { get; set; }
        public String? address1_city { get; set; }
        public Guid? entityimageid { get; set; }
        public String? middlename { get; set; }
        public Guid? systemuserid { get; set; }
        public Int32? importsequencenumber { get; set; }
        public Guid? address1_addressid { get; set; }
        public String? defaultmailboxname { get; set; }
        public String? address2_city { get; set; }
        public String? parentsystemuseridname { get; set; }
        public Decimal? address2_latitude { get; set; }
        public String? territoryidname { get; set; }
        public DateTime? latestupdatetime { get; set; }
        public String? address1_fax { get; set; }
        public String? businessunitidname { get; set; }
        public Guid? azureactivedirectoryobjectid { get; set; }
        public Guid? address2_addressid { get; set; }
        public String? address1_country { get; set; }
        public String? defaultodbfoldername { get; set; }
        public String? internalemailaddress { get; set; }
        public String? address2_line3 { get; set; }
        public String? nickname { get; set; }
        public Decimal? address1_longitude { get; set; }
        public String? applicationiduri { get; set; }
        public String? address2_country { get; set; }
        public String? lastname { get; set; }
        public Guid? activedirectoryguid { get; set; }
        public Int32? timezoneruleversionnumber { get; set; }
        public String? traversedpath { get; set; }
        public String? disabledreason { get; set; }
        public String? yomimiddlename { get; set; }
        public String? address1_name { get; set; }
        public String? skills { get; set; }
        public String? address1_stateorprovince { get; set; }
    }
}